### ISSUE TITLE
[Bug] Functional tests have a strong reliance on non-determinism

### ISSUE THREAD

**Issue by huitseeker** [diem/diem#430]
# 🐛 Bug
In a tangential diff I've found a strange dependency:
https://github.com/libra/libra/pull/429/files#diff-ba0d53e0f136066b6b052d26efb96de6R49

This diff has nothing to do with functional tests, but at the line above I noticed functional tests fail if I make the `e2e_tests::Account::new()` function deterministic (i.e. return the same value in successive calls),

Here's a run of the output: https://gist.github.com/huitseeker/e336d21cfdd7ce81323d9273b06dab63

Interestingly, the single-account gas_submitted_too_low.mvir test fails (!)

**Comment by vgao1996** [comment]
Hmm... from my understanding this is expected behavior: functional tests expect each call to `Account::new` to return a distinct account, which will later be used to simulate transactions involving multiple parties. Here's an example
- There are two accounts aliased Alice & Bob
- Alice sends some money to Bob (txn 1)
- Alice sends a txn with assertions to check her account balance is less than (original amount - amount payed)
- Bob sends a txn with assertions to check his account balance is exactly (original amount + amount payed)
If these two turns out to be the same account, then the assertions will fail.

Could I ask why you need to make this function deterministic?

**Comment by vgao1996** [comment]
> single-account gas_submitted_too_low.mvir test fails

This is indeed an interesting case. I'm having a look at the log right now.

**Comment by huitseeker** [comment]
We are not making `Account::new()` deterministic, in fact the code suggested in this PR patches `Account::new()` and reproduces the behavior : each call to `Account::new()`  returns a distinct account. Hence functional tests pass in the PR.

Context:
- there are several ongoing efforts to make tests deterministic, 
- in the new crypto API, the recommended code path either lets you get results from a PRNG with default test seed:
```
compat::generate_keypair(None)
```
Or from a `&mut rng` where `rng` is an rng controlled and seeded by you, the test writer.
```
compat::generate_keypair(&mut rng)
```

What I think the issue is here:
- the tests rely on successive calls being distinct, 
- this is very often the case, but not always,
- this assumption is made implicit,
- it's hard to debug when it goes wrong,
- the rust-idiomatic intuition is to think that a parameter-less `Account::new` provides a single, deterministic default value.

=> Code that would use `Account::with_keypair` instead of `Account::new()` with an explicit collection of distinct key pairs would help make this behavior more understandable.

**Comment by vgao1996** [comment]
> single-account gas_submitted_too_low.mvir test fails

My (very possible) guess: in this test functional tests try to create two accounts:
- Alice, with very low account balance
- a default account with fairly high default account balance

It will then try to register them with the transaction executor. However if these two turns out to have the same address, I would expect things to go wrong. Looks like in your case the default account won, and therefore the transaction was executed successfully.

**Comment by vgao1996** [comment]
@huitseeker ah I get your point. It's clearly a better approach I manage my own RNG and use it to generate the key pairs explicitly. I'll find some time to implement this.

> the rust-idiomatic intuition is to think that a parameter-less Account::new provides a single, deterministic default value.

For now I would suggest we rename the current `Account::new` to something like `Account::random`. We can add a new `Account::new` that takes a key pair.

**Comment by bob-wilson** [comment]
Did this ever get fixed?

**Comment by bob-wilson** [comment]
@vgao1996 Ping

**Comment by vgao1996** [comment]
@bob-wilson this was fixed a long time ago.

**Comment by bob-wilson** [comment]
No concerns. That's what I thought. I was just waiting for you to confirm and close this out.
