### ISSUE TITLE
[compiler][bug] move_to in transaction script causes crash

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#4577]
@moeziniaf ran into this the other day.

Repro:

Adding this to stdlib/transaction_scripts 

```
script {
use 0x1::LibraAccount;

fun test<Token>(account: &signer) {
    let withdraw_cap = LibraAccount::extract_withdraw_capability(account);
    move_to(account, withdraw_cap);
}
}
```

produces

```
Creating stdlib blob ... (took 2.131s)
Staging transaction scripts ... thread '<unnamed>' panicked at 'ICE invalid struct definition lookup', language/move-lang/src/to_bytecode/context.rs:240:9
```

**Comment by sblackshear** [comment]
Similar problem with 

```
script {
use 0x1::LibraAccount;

fun test<Token>() {
    borrow_global<LibraAccount::LibraAccount>(0x1);
}
}
```, 

so guessing it's related to using any module builtin in a tx script.

**Comment by bob-wilson** [comment]
I'll investigate this.

**Comment by tnowacki** [comment]
It's possible (and likely) that my changes to aliasing broke this somehow. And there were insufficient tests (in the past I couldn't really test this easily because scripts had to be in their own file)

**Comment by bob-wilson** [comment]
I think I understand what's going wrong here, but after digging into it, I believe these examples would have never worked. I believe you can only use module builtins with the types declared inside that module. (I checked to confirm that in the original Move whitepaper, and I'm not aware that the situation has changed.) Scripts are by definition not inside any module, so you cannot use these builtins in scripts. Obviously the compiler needs to give decent error messages instead of crashing, though.

If someone can confirm my understanding of the situation, I'd appreciate that!

**Comment by tnowacki** [comment]
> I think I understand what's going wrong here, but after digging into it, I believe these examples would have never worked.

That is correct. These examples should give an error message in place of the compiler crashing. There *should* already be a mechanism in place that will give these error messages, so we just need to make sure the compiler doesn't crash before that error message is triggered
