### ISSUE TITLE
[Feature Request] suppress an unused schema warning

### ISSUE THREAD

**Issue by junkil-park** [diem/diem#5209]
# 🚀 Feature Request

Provide a way to suppress an "unused schema warning"

## Motivation

One pattern being used in our specs now is to add a "AbortsIf" schema in Roles and use it in another module as follows:
```
/// The permission "BurnCurrency(type)" is granted to TreasuryCompliance [B13].
apply Roles::AbortsIfNotTreasuryCompliance{account: tc_account} to register_SCS_currency<CoinType>;
```

However, Prover produces an "unused schema warning" for the schema which is defined in Roles, but actually supposed to be used in other modules.

**Comment by wrwg** [comment]
Unused schema warnings can be prevented by doing `UNUSEDSchemaName`. But we may want a more Move idiomatic way to do this.

In fact the use case this would not cover is where we have a schema intended for use in other modules. We also do not check for helper function and that is by design because they may also be used outside of the module.

Consider instead to do the warnings more targeted, e.g. if `apply S to *X` does not have any match.

**Comment by wrwg** [comment]
Another option would be to just add a pragma to suppress warnings.
