### ISSUE TITLE
[Bug] Imported schemas give error message pointing to schema file, not the file with the error.

### ISSUE THREAD

**Issue by DavidLDill** [diem/diem#5737]
# 🐛 Bug

In LibraConfig.move, I included Roles::AbortsIfNotLibraRoot instead of the function by the same name in CoreAddresses.  The resulting error message directed me to line 459 of Roles.move, when the error trace
was for LibraConfig.move (see PR #5664).

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by wrwg** [comment]
The information is in the execution trace, but it could be better visualized.

**Comment by wrwg** [comment]
This by design. We are pointing to the condition which has failed, and if that condition comes from a different module, so will be the reference to it. To see which function is verified when the failure happens, the execution trace provides the required info.

Feel free to re-open if I misunderstood.
