### ISSUE TITLE
[Bug] Bors bot leaves PRs in wrong state

### ISSUE THREAD

**Issue by yanivmo** [diem/diem#7226]
# 🐛 Bug

The very friendly Bors bot complains that unless "Allow edits from maintainers" is checked, it cannot change the PR status properly.

![image](https://user-images.githubusercontent.com/3540009/104512169-7947da80-55f6-11eb-8742-9a9b90fac679.png)

However, this option is not available in many cases. To my understanding, it is visible only if I open a PR from my private fork. When it is from my organization, the option is not visible at all.

## To reproduce

Here's an example: https://github.com/diem/diem/pull/7141
I really tried to find the checkbox but it just wasn't there.

## Expected Behavior

Merged PRs should better appear merged, this way or another, because with all the arcane automatic messages in PRs, it is really hard to understand whether a PR was actually accepted or not.

**Comment by bmwill** [comment]
Hey @yanivmo this was brought to my attention some time last week when Bors simply rejected such PRs, refusing to merge them. The fix that I deployed last week (and the current behavior you are seeing) is unfortunately the only remediation that exists due to limitations with Github itself.

Theres a few things at play here:
1. When the Diem project was started it was decided that we would keep a strictly linear git history, meaning that any changes would be rebased onto the latest `master` instead of "merging" them using a merge commit.
2. Because we rebase the commits that are a part of a PR end up having different hashes than the ones that are added to `master` making it impossible for Github to understand that such commits "merge" in a PR. In order to convince Github to mark a PR as "Merged", where possible, Bors will use the "maintainer mode" to update the PR in-place with the result of the rebase prior to pushing the changes to `master`, effectively tricking Github into marking the PR as "Merged".
3. In the event that "maintainer mode" isn't available Bors now falls back to simply pushing the changes to `master` and closing the related PR. It seems like there are certain circumstances where such a "maintainer mode" isn't available (and permission can't be given to bors to update the PR in-place), from experimentation these seem to be PRs originating from forks of private repositories and from forks of public repositories where the fork is an organization repo instead of a user one. I speculate the reason for the latter restriction is due to the fact that checking such a box give folks with write permissions to the upstream repo, write access to forked repo which could be awkward when that repo is organization owned.

So unfortunately this isn't a bug inside of Bors but rather a failing of Github and there's not much more that we can do at this time. Thankfully this is really just a cosmetic issue and does not affect the actual merging of PRs into `master`.

Let me know if any of that didn't make sense or how else I can help you.

**Comment by yanivmo** [comment]
Thanks for such an elaborate answer on such a minor problem.

I am not even sure of it's feasible, but how about these theoretical improvements:

1. If it's possible to detect the type of the repository that created the PR, then maybe the message could be adjusted? It was quite confusing to look for this evasive checkbox.
2. If not, at least rephrase the message so it is more clear that this option is not always available.
3. How about doing a normal merge if it is fast-forwardable. This way the history is still linear but the hashes are not changed. Will solve the issue in some of the cases, at least.

**Comment by bmwill** [comment]
Of course! I've actually thought quite a bit about the problem and wished there was a better solution give the current state of things. As for your suggestions:

1. Might be doable but I would have to do some digging into Github's API to be sure.
2. At the very least we could do this, thats just an easy update to the bors-rs/bors and then doing a redeploy.
3. Isn't practically feasible given the commit rate in the diem repo as PRs essentially become out of date if there is anything ahead of it in the merge queue.
