### ISSUE TITLE
signed the CLA already, but your status is still pending

### ISSUE THREAD

**Issue by s3uleman** [diem/diem#8356]
response = Thank You!
You have authorized your GitHub account and successfully signed the Individual Contributor License Agreement.

but (cla-unsigned) still persist.

**Comment by modocache** [comment]
Hi, sorry you experienced this issue. It looks like the pull request where you were asked to sign the CLA, https://github.com/diem/diem/pull/7945, did in fact never get an updated status, which is odd... I think this system has been improved since then. Hopefully you'll choose to submit another PR in the future, at which point I hope this works correctly (ping me if it doesn't!). Until then, I'll close this issue.
