### ISSUE TITLE
[Feature Request] optimize Ed25519PublicKey deserialization

### ISSUE THREAD

**Issue by zekun000** [diem/diem#8619]
# 🚀 Feature Request

## Motivation

Deserialize a pubkey goes through a validation function https://github.com/diem/diem/blob/main/crypto/crypto/src/ed25519.rs#L362-L390 which is pretty slow.

it takes ~55ms to deserialize 1000 keys (a typical block size) which we need to do twice a round (proposer -> follower, follower -> TCB), thus may be worth optimizing.

alternative can be to delay the validation to signature check phase.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by sblackshear** [comment]
@emmazzz and I were actually just discussing representing how representing public keys and signatures as `Vec<u8>` + delaying the validation to the signature checking phase would make it easier to extend Diem with new crypto schemes. Today, this is already pretty easy because you just need to add a new variant to the `TransactionAutheticator` enum, but if the key + signature types were plain bytes, it would (I think) be possible for other instantiations of DIem to add new crypto without changing the Diem repo at all.

**Comment by emmazzz** [comment]
Right this is related to the work we are doing to make Diem more extendable. One of the goals is to make it easier to add new authentications schemes outsides of Diem repo. And as Sam said, delaying the deserialization of public keys and sigs will do the job as well as improve the performance.

**Comment by zekun000** [comment]
@sblackshear @emmazzz awesome, is the bytes going to be self-describing the crypto scheme (like the enum) or having the schema living somewhere else?

I saw https://github.com/multiformats/multicodec a few days ago, not sure if it's interesting

**Comment by sblackshear** [comment]
> @sblackshear @emmazzz awesome, is the bytes going to be self-describing the crypto scheme (like the enum) or having the schema living somewhere else?

I think it will need to be self-describing, but the schema can live outside of the Diem repo. To push this a bit further, my thinking is that in a maximally pluggable version of Diem, an "instantiation" would provide something like:

- genesis modules
- Move adapter (component that takes a tx as input, passes it to the Move VM, produces a ChangeSet)
- transaction format (understood by the adapter, opaque bytes to everyone else) including public keys, signature, ...

I think of "Opaque pubkeys/signature" is a slightly less extreme/flexible version of "opaque tx format", and perhaps one that would be easier to achieve in the short term (since refactoring to make `Transaction` opaque would be a huge project...).

**Comment by sblackshear** [comment]
> I saw https://github.com/multiformats/multicodec a few days ago, not sure if it's interesting

Very cool, will take a look!

**Comment by matbd** [comment]
@kchalkias will know better but I suspect key validation was meant to detect invalid public keys early (e.g in config files) so delaying it might not be very useful.

For a quick perf win, one could memoize the last N valid public keys (say N=1000 to be safe) within the crypto library.

**Comment by zekun000** [comment]
@matbd yes, we could add a cache for easy wins.

the delaying part could help is mainly because we parallelize the signature verification unlike the sequential deserialization. (the amount of work is the same but it'd be much faster with multi threads)

**Comment by zekun000** [comment]
https://github.com/diem/diem/pull/8950#event-5181752312
