### ISSUE TITLE
Client incompatibility between release 1.2 and release 1.3

### ISSUE THREAD

**Issue by dmitri-perelman** [diem/diem#8643]
When trying to run a system that is using client from `diem-sdk = { git = "https://github.com/diem/diem", branch = "release-1.2" }` against the validator that is running release 1.3, you get the following error:
```
Error { inner: Inner { kind: Decode, source: Some(Error("unknown variant `treasury_compliance`, expected one of `unknown`, `child_vasp`, `parent_vasp`, `designated_dealer`", line: 0, column: 0)), json_rpc_error: None } }
```

Seems that the `treasury_compliance` role cannot be parsed by the old client.

**Comment by bmwill** [comment]
Looking at the difference between the code in `json-rpc/types/src/views.rs` for the two difference releases it looks like the TreasuryCompliance Role didn't exist in the 1.2 release but does in the 1.3 release. So the old client wouldn't be able to properly understand, parse and interpret that role since the old client doesn't know about it.

The bigger issue this highlights is that the deserialization failed and we still want deserialization to succeed in this case. This should be fixed by tagging the `Unknown` Role with `#[serde(other)]`.
